services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout-backend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    # user: '${UID}:${GID}'
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: workout-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    shm_size: 128mb

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout-prisma-studio
    ports:
      - '5555:5555'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: ['npx', 'prisma', 'studio', '--hostname', '0.0.0.0']
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
