-- AlterTable
ALTER TABLE "public"."Workout" ADD COLUMN     "isPaused" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastPauseStartTime" TIMESTAMP(3),
ADD COLUMN     "pauseDuration" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
